version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "orderApi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8s0fwcacbs0u"
s3_prefix = "orderApi"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
